#!/bin/bash
archi="amd64"
#archi="i386"

debian_version="stretch"

dist_name="Ermitage"

iso_name="Ermitage-Debian9-amd64.iso"

boot_default="ram"
#boot_default=""
#boot_default="failsafe"

livework="./livework"

source_list="deb http://http.debian.net/debian stretch main contrib non-free"
#mirror="http://ftp.us.debian.org/debian" # use by debootstrap
#sources_list="deb $mirror ${debian_version} main" # if not empty, replace /etc/apt/sources.list by this content
